### ISSUE TITLE
[FEAT] <Support for transmission-vpn>

### ISSUE THREAD

**Issue by eyalspier** [linuxserver/docker-swag#358]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I am currently not using the base "transmission" image, but the transmission-vpn image on my setup. This doesn't appear to be supported yet. Could this be added?

### Reason for change

It helps me use transmission behind a VPN server for extra anonymity and security

### Proposed code change

Copy the config files for transmission, name them *transmission-vpn* instead and change the corresponding entries.

**Comment by nemchik** [comment]
I don't think we'll add this. It's possible for users to vary the name of their container, ex:
```
transmission-vpn
transmissionvpn
transmission
```
(any of those, or really any name could be the container name)

The easiest option is to just modify the existing transmission template to match the container name and port you are using. The endpoints (location blocks) should all match otherwise.

**Comment by eyalspier** [comment]
Hi Erik,
Thanks for your prompt response! Did it and worked like a charm!
