### ISSUE TITLE
[FEAT] Simpler nginx configuration structure

### ISSUE THREAD

**Issue by jerkstorecaller** [linuxserver/docker-swag#402]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

abcdef

### Reason for change

swag's nginx config scheme is just ridiculously complex. I can tell whoever wrote it is a big fan of CLOUD SCALE MODULARIZATION. But your users are not Google, they're home users with 5 apps. They have work in the morning. I don't want to jump all over the filesystem opening 10 different configuration files in different directories just to try to understand  what the server is doing. Did worker_processes.conf which only contains "worker_processes 1;" really need to be its own file? I get that it's autogenerated but couldn't a sed on nginx.conf have taken care of that?

I nuked the whole config dir thing and went with a simple nginx.conf and a 2nd file for shared settings. Now I can breathe. Except when the container restarts, all those deleted files are recreated. 

May I suggest not polluting the root? (/config/nginx/). Only have a single nginx.conf there, and move literally everything else to a subdirectory.

Also, even for your own complex structure, why not put the samples in a separate directory? There's 296 files in proxy-confs, no one is gonna be able to find their own config with 'ls', and they can't tab-complete the filename in one go either.

What it should look like IMO:

```
/config/nginx
	nginx.conf
	ssl.conf
		enabled-confs/
			heimdall.subdomain.conf
			qbittorrent.subdomain.conf
		samples/
			...your bazillions of files				
```

And make the user copy what they need from samples/ to enabled-confs/.

P.S. I can tell whoever created the nginx config structure also created the Github issue template. I think there's a pill for that now :laugh

**Comment by thespad** [comment]
Aside from the needless jabs at the various people who have maintained swag, what you're asking for is basically a new image to meet your preferences.

We design around the idea that we should never touch a user's configs in an existing install, unless there is no other option. `sed` can break, there are all kinds of edge cases we can't account for, if we start trying to selectively modify one massive nginx.conf it's only a matter of time before we hose someone's otherwise working setup.

That's not to say there *isn't* anything about the current image that can be improved, but any changes have to be weighed against the impact they would have on any existing installs, mods, or 3rd party scripts that expect the current layout. Sometimes the reality is just that we're limited by past decisions and the cost of fixing them isn't justifiable.

If you have constructive suggestions that aren't just "I don't like it this way", and can make them without the snide remarks, we're happy to consider them.

**Comment by jerkstorecaller** [comment]
Yes, I kinda figured you can't change the configuration structure and break all the existing containers, it was more of a general review.

Those weren't intended as jabs, more like friendly ribbing, which I didn't think would be inappropriate in a geeky hobby project rather than a bland Corporate-American thing. There was a laughing emoji in the OP but I see I forgot the closing colon so it didn't display.

Anyway thanks to the people who made swag.

**Comment by aptalca** [comment]
With regards to certain things being broken out into their own separate files, that's because some of those directives need to be added to various server or location blocks. Having them in a separate file allows for using nginx's `include` directive to insert them many times while only having to change the value in one place.

**Comment by nemchik** [comment]
Not too seem like a dog pile, but we have actually internally discussed the folder structure quite a bit in efforts to make things more organized and cleaner for users to manage while still giving us the benefits of using includes everywhere we need them. The main blocker for that is existing configs and over engineering. If we move things around from where they are, all the proxy configs that include specific file paths for those configs will need to be adjusted. Per spad's comment, we avoid forcing changes on the existing user configs (ex: automatically replacing file paths) whenever possible unless there's a breaking change that requires it.

All that being said we're not opposed to discussing ideas on how to improve, and not entirely opposed to a full revamp with drastic changes if it's justified. Another thing to keep in mind is the nginx base is where a lot of the configs exist, and they affect many of our images (not just swag).

I'm going to close this as completed, but feel free to continue commenting here or chat us on discord if you have ideas for changes.
