### ISSUE TITLE
[FEAT] support Netlify DNS API

### ISSUE THREAD

**Issue by dannysauer** [linuxserver/docker-swag#411]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Support Netlify DNS API.

The API is reasonably well-documented:
- https://docs.netlify.com/api/get-started/
- https://open-api.netlify.com/#tag/dnsZone/operation/createDnsRecord
- https://open-api.netlify.com/#tag/dnsZone/operation/deleteDnsRecord

### Reason for change

Netlify is not terrifically unpopular, and does have a free plan which is not bad for personal web site hosting.  I suspect adding support for another pretty typical REST API isn't a huge amount of work, though I'm not yet familiar enough with the codebase to actually _do_ that work.

**Comment by Roxedus** [comment]
We rely on there to be certbot plugins to be able to offer support.

**Comment by dannysauer** [comment]
I was just looking, and figured out that this is actually a certbot feature request. :D

**Comment by dannysauer** [comment]
Appears that https://github.com/alexzorin/certbot-dns-multi supports netlify.  So would this be as simple as including that plugin and adding a dns-multi.ini?

**Comment by nemchik** [comment]
I reviewed the multi plugin and it has quite a bit of overlap with existing plugins. I don't think the right call is to replace the existing plugins with the multi plugin, and I feel like having them side by side can lead to confusion (ex: should i use the duckdns plugin or the duckdns config with the multi plugin).

It would be preferable if there were a standalone plugin for netlify.

**Comment by dannysauer** [comment]
Seems like adding multi in place of a bunch of stand-alone plugins would provide broader support with less work, but that's up to the project. They're all grouped together there to begin with because they're basically all the same thing with a different URL. 😂

**Comment by nemchik** [comment]
There even seems to be overlap with official plugins. We've got an open issue https://github.com/linuxserver/docker-swag/issues/422 where the official ovh plugin is not working correctly due to a 3rd party plugin dependency conflict. We're considering options, but it could mean anything from removing the one 3rd party plugin all the way to removing all 3rd party plugins. No decisions have been made. Users can also install any plugin they want using our https://github.com/linuxserver/docker-mods/tree/universal-package-install mod, so you can actually use the multi plugin right now if you wish.

I understand and agree with the idea that the multi plugin is less to maintain, but the changes required to use it will mean adapting our current package to accommodate the difference in required variables, and that may be impossible in some cases thus requiring users to make changes. We avoid breaking changes as much as possible, but sometimes they are necessary.

Lastly, I notice this plugin seems to use another library https://go-acme.github.io/lego/ underneath, which i understand, but it does seem a bit odd (lego is a standalone acme client, typically used in place of certbot).
