### ISSUE TITLE
[FEAT] Specify RSA Key Size

### ISSUE THREAD

**Issue by alexfornuto** [linuxserver/docker-swag#477]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

First off, thanks for the project! 

I would like an environment variable to set the key size when getting certificates from LE. 

### Reason for change

More bits == more secure, depending on who you ask.

### Proposed code change

A code change was proposed and then closed in favor of "a different way in the near future" ([ref](https://github.com/linuxserver/docker-swag/pull/237#issuecomment-1427072226)).

If that change was implemented, it wasn't documented in the README (as far as I can see), and if it wasn't I would politely suggest that "near future" has passed and attention is given back to the original PR, #237.

As an aside, if changes were made a reference to them in that PR thread would have helped then-future now-present folks like myself find it.

**Comment by alexfornuto** [comment]
If you need feedback from OP, I'm happy to provide it.

**Comment by ckantor8** [comment]
I would also strongly support this! Being able to get 4k certs to match my 4k dhparams would be great

**Comment by alexfornuto** [comment]
It has not had recent activity because it's not been addressed. If there's a "note stale" tag, perhaps it should be added?

**Comment by alexfornuto** [comment]
Not stale, just ignored.

**Comment by alexfornuto** [comment]
Adding another comment with more text, since my previous comment hasn't yet triggered the bot to remove the autoclosing tag. This issue is _not_ waiting for feedback from OP (me), it just needs to be triaged.

**Comment by nemchik** [comment]
Sorry I didn't see this sooner. It is currently possible, but here's a few notes:

The default for generating new certs since https://github.com/linuxserver/docker-swag/pull/339 is `ecdsa` which doesn't use the `rsa` key size. If you have been renewing a cert that was originally issued prior to that PR merging it could still be `rsa`. Renewals keep the original cert settings. If you want a new `ecdsa` cert; delete `/config/keys` and `/config/etc` and restart the container.

If for some reason you want to use `rsa` instead of `ecdsa` you can delete `/config/keys` and `/config/etc/letsencrypt/renewal`, modify `/config/etc/letsencrypt/cli.ini` by following the information in the official certbot docs here https://eff-certbot.readthedocs.io/en/latest/using.html#configuration-file and specify the key type and key size you would like to use, and then restart your container. It should generate a new cert to your specifications. If you have trouble, our recommendation will be to delete your custom config and let SWAG generate a new default config which will use `ecdsa` by default.
